name: 'ğŸ“™ Chromatic'

on:
  push:
    branches-ignore:
      - 'main'

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ğŸ¥Ÿ Setup Bun
        uses: antongolub/action-setup-bun@v1
      - name: ğŸ“¦ install depencies
        run: bun i
      - name: â˜ï¸ Publish to Chromatic
        uses: chromaui/action@v1
        with:
          exitOnceUploaded: true
          onlyChanged: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        env:
          DATABASE_URL: file:./db.sqlite
